CREATE DEFINER=`root`@`localhost` PROCEDURE `SPOptimizeAll`()
BEGIN
	ANALYZE TABLE `db_lafamigliapizzeriadelivery`.`adicional`, 
				  `db_lafamigliapizzeriadelivery`.`adicional_hst`, 
				  `db_lafamigliapizzeriadelivery`.`cliente`, 
				  `db_lafamigliapizzeriadelivery`.`cliente_hst`, 
				  `db_lafamigliapizzeriadelivery`.`endereco`, 
				  `db_lafamigliapizzeriadelivery`.`enderecopadrao`, 
				  `db_lafamigliapizzeriadelivery`.`itempedidoadicional`, 
				  `db_lafamigliapizzeriadelivery`.`itempedidoadicional_hst`, 
				  `db_lafamigliapizzeriadelivery`.`itempedidopizza`, 
				  `db_lafamigliapizzeriadelivery`.`itempedidopizza_hst`, 
				  `db_lafamigliapizzeriadelivery`.`itempizzasabor`, 
				  `db_lafamigliapizzeriadelivery`.`itempizzasabor_hst`, 
				  `db_lafamigliapizzeriadelivery`.`pedido`, 
				  `db_lafamigliapizzeriadelivery`.`pedido_hst`, 
				  `db_lafamigliapizzeriadelivery`.`saborborda`, 
				  `db_lafamigliapizzeriadelivery`.`saborborda_hst`, 
				  `db_lafamigliapizzeriadelivery`.`saborpizza`, 
				  `db_lafamigliapizzeriadelivery`.`saborpizza_hst`, 
				  `db_lafamigliapizzeriadelivery`.`statuspedido`, 
				  `db_lafamigliapizzeriadelivery`.`tamanhopizza`, 
				  `db_lafamigliapizzeriadelivery`.`tamanhopizza_hst`, 
				  `db_lafamigliapizzeriadelivery`.`tipousuario`, 
				  `db_lafamigliapizzeriadelivery`.`usuario`, 
				  `db_lafamigliapizzeriadelivery`.`usuario_hst`;
	SET GLOBAL innodb_optimize_fulltext_only=1, innodb_ft_num_word_optimize=2000;
    OPTIMIZE TABLE `db_lafamigliapizzeriadelivery`.`adicional`, 
				   `db_lafamigliapizzeriadelivery`.`adicional_hst`, 
                   `db_lafamigliapizzeriadelivery`.`cliente`, 
                   `db_lafamigliapizzeriadelivery`.`cliente_hst`, 
                   `db_lafamigliapizzeriadelivery`.`endereco`, 
                   `db_lafamigliapizzeriadelivery`.`enderecopadrao`, 
                   `db_lafamigliapizzeriadelivery`.`itempedidoadicional`, 
                   `db_lafamigliapizzeriadelivery`.`itempedidoadicional_hst`, 
                   `db_lafamigliapizzeriadelivery`.`itempedidopizza`, 
                   `db_lafamigliapizzeriadelivery`.`itempedidopizza_hst`, 
                   `db_lafamigliapizzeriadelivery`.`itempizzasabor`, 
                   `db_lafamigliapizzeriadelivery`.`itempizzasabor_hst`, 
                   `db_lafamigliapizzeriadelivery`.`pedido`, 
                   `db_lafamigliapizzeriadelivery`.`pedido_hst`, 
                   `db_lafamigliapizzeriadelivery`.`saborborda`, 
                   `db_lafamigliapizzeriadelivery`.`saborborda_hst`, 
                   `db_lafamigliapizzeriadelivery`.`saborpizza`, 
                   `db_lafamigliapizzeriadelivery`.`saborpizza_hst`, 
                   `db_lafamigliapizzeriadelivery`.`statuspedido`, 
                   `db_lafamigliapizzeriadelivery`.`tamanhopizza`, 
                   `db_lafamigliapizzeriadelivery`.`tamanhopizza_hst`, 
                   `db_lafamigliapizzeriadelivery`.`tipousuario`, 
                   `db_lafamigliapizzeriadelivery`.`usuario`, 
                   `db_lafamigliapizzeriadelivery`.`usuario_hst`;
		SET GLOBAL innodb_optimize_fulltext_only=True;
END